services:
  rabbitmq:
    image: rabbitmq:management
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 30s
      timeout: 6s
      retries: 5
    ports:
      - "5672:5672" # Porta padr찾o para conex천es AMQP
      - "15672:15672" # Porta padr찾o para o painel de controle do RabbitMQ
    networks:
      - localnet      
  postgres:
    image: postgres:14-alpine
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - 5432:5432
    volumes:
      - ~/apps/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=Rent@bike2024
      - POSTGRES_USER=rentbike_user
      - POSTGRES_DB=RentBikeDB
    networks:
      - localnet
  minio:
    hostname: minio
    image: minio/minio:latest
    container_name: minio
    ports:
      - "9001:9001" # Porta padr찾o do MinIO
    environment:
      - MINIO_ACCESS_KEY=minio
      - MINIO_SECRET_KEY=Rent@bike2024
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data
    networks:
      - localnet
  api: 
    build: ./src/RentBike.API      
    container_name: container_ewerton
    ports:
      - 8080:80
      - 8081:443
    networks:
      - localnet
    depends_on:
      postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
volumes:
  minio_data:
    driver: local
networks:
  localnet:
    driver: bridge