services:
  rabbitmq:
    image: rabbitmq:management
    ports:
      - "5672:5672" # Porta padr찾o para conex천es AMQP
      - "15672:15672" # Porta padr찾o para o painel de controle do RabbitMQ
  mssql:
    container_name: mssql-db
    hostname: mssql-db
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      ACCEPT_EULA: 'Y'
      MSSQL_SA_PASSWORD: 'Rent@bike2024'
      MSSQL_DATA_DIR: /var/opt/mssql/data
      MSSQL_PID: 'Developer' 
      MSSQL_TCP_PORT: 1433
    ports: 
      - "1433:1433"
    volumes:
      - ./data:/var/opt/mssql/data
      - ./log:/var/opt/mssql/log
      - ./secrets:/var/opt/mssql/secrets
  postgres:
    image: postgres:14-alpine
    ports:
      - 5432:5432
    volumes:
      - ~/apps/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=Rent@bike2024
      - POSTGRES_USER=rentbike_user
      - POSTGRES_DB=RentBikeDB
  minio:
    hostname: minio
    image: minio/minio:latest
    container_name: minio
    ports:
      - "9001:9001" # Porta padr찾o do MinIO
    environment:
      - MINIO_ACCESS_KEY=minio
      - MINIO_SECRET_KEY=Rent@bike2024
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data
volumes:
  minio_data:
    driver: local